# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='challenge',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
            preserve_default=False,
        ),
    ]
