# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20160621_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
