# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20160621_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.CharField(default='saharsh', max_length=100),
            preserve_default=False,
        ),
    ]
