# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20160701_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='color',
            field=models.CharField(default='khaki', max_length=200),
        ),
    ]
